size_nlp = "sm"
num_recommendations = 10
default_threshold = 0.3

date_pattern = "(\d{2}|\d{1})(\s{1}|-|/)"+\
"((Jan(uary)?|(Feb(ruary)?|Ma(r(ch)?|y)|Apr(il)?|Jun(e)?|Jul(y)?|Aug(ust)|(Sept|Nov|Dec)(ember)?)|Oct(ober)?)|(\d{1}|\d{2}))"+\
               "(\s{1}|-|/)(\d{4}|(')?\d{2})"

abbr_dict = {
    'CEN': 'European Committee for Standardisation',
    'EEC': 'European Economic Commision',
    'EU': 'European Union',
    'EC': 'European Commission',
    'NATO': 'North Atlantic Treaty Organization',
    'USA': 'United States of America',
    'UK': 'United Kingdom',
    'PGI': 'Principal Global Indicators',
    'PDO': 'Protected designation of origin',
    'EFSA': 'European Food Safety Authority'
}
abbr_expand = "|".join(list(abbr_dict.keys()))
DEBUG = True
wordBased = True

queries = [
        'the european council of june 2008 referred again to the sustainability criteria and the development of second-generation biofuels, and underlined the need to assess the possible impacts of biofuel production on agricultural food products and to take action, if necessary, to address shortcomings',
        '(11) it is necessary to set transparent and unambiguous rules for calculating the share of energy from renewable sources and for defining those sources',
        '(15) the starting point, the renewable energy potential and the energy mix of each member state vary',
        'the majority of member states apply support schemes that grant benefits solely to energy from renewable sources that is produced on their territory',
        'cyprus and malta, due to their insular and peripheral character, rely on aviation as a mode of transport, which is essential for their citizens and their economy',
        'as a result, cyprus and malta have a gross final consumption of energy in national air transport which is disproportionally high, i',
        'however, to avoid a net increase in greenhouse gas emissions through the diversion of existing renewable sources and their complete or partial replacement by conventional energy sources, only electricity produced by renewable energy installations that become operational after the entry into force of this directive or by the increased capacity of an installation that was refurbished after that date should be eligible to be counted',
        '(56) guarantees of origin do not by themselves confer a right to benefit from national support schemes',
        'particular attention should be paid to renewable energy projects that will contribute to a significant increase in security of energy supply in the community and neighbouring countries',
        '(59) interconnection among countries facilitates integration of electricity from renewable energy sources',
        'however, this does not imply any obligation on the part of member states to support or introduce purchase obligations for energy from renewable sources',
        '(62) the costs of connecting new producers of electricity and gas from renewable energy sources to the electricity and gas grids should be objective, transparent and non-discriminatory and due account should be taken of the benefit that embedded producers of electricity from renewable energy sources and local producers of gas from renewable sources bring to the electricity and gas grids',
        'such sustainability criteria should therefore be included in this directive',
        '(74) the incentives provided for in this directive will encourage increased production of biofuels and bioliquids worldwide',
        '(80) it is necessary to lay down clear rules for the calculation of greenhouse gas emissions from biofuels and bioliquids and their fossil fuel comparators',
        'the commission should encourage those sources to address, when they update their work, emissions from cultivation, the effect of regional and climatological conditions, the effects of cultivation using sustainable agricultural and organic farming methods, and the scientific contribution of producers, within the community and in third countries, and civil society',
        '(86) in order to permit the achievement of an adequate market share of biofuels, it is necessary to ensure the placing on the market of higher blends of biodiesel in diesel than those envisaged by standard en590/2004',
        'such plans could include estimated costs and benefits of the measures envisaged, measures relating to the necessary extension or reinforcement of the existing grid infrastructure, estimated costs and benefits to develop energy from renewable sources in excess of the level required by the indicative trajectory, information on national support schemes and information on their use of energy from renewable sources in new or renovated buildings',
        '(d) ‘hydrothermal energy’ means energy stored in the form of heat in surface water',
        '(m) ‘actual value’ means the greenhouse gas emission saving for some or all of the steps of a specific biofuel production process calculated in accordance with the methodology laid down in part c of annex v',
        'by 31 december 2011, the commission shall present, if appropriate, a proposal permitting, subject to certain conditions, the whole amount of the electricity originating from renewable sources used to power all types of electric vehicles to be considered',
        'in response to a national renewable energy action plan or to an amended national renewable energy action plan, the commission may issue a recommendation',
        'for the purposes of this calculation, the contribution of each energy source shall be calculated on the basis of its energy content',
        'and (b) added to the amount of energy from renewable sources that is taken into account in measuring compliance by another member state accepting the transfer with the requirements of (1) and (2)',
        'a statistical transfer shall not affect the achievement of the national target of the member state making the transfer',
        'two or more member states may cooperate on all types of joint projects relating to the production of electricity, heating or cooling from renewable energy sources',
        '(d) after it becomes operational, the interconnector will be used for the export to the community, in accordance with paragraph 2, of electricity generated from renewable energy sources',
        'the proportion or amount of electricity produced by any installation in the territory of a third country, which is to be regarded as counting towards the national overall target of one or more member states for the purposes of measuring compliance with , shall be notified to the commission',
        'for the purposes of measuring target compliance with the requirements of this directive concerning national overall targets, the amount of electricity produced from renewable energy sources notified in accordance with paragraph 1(b) shall be added to the amount of energy from renewable sources that is taken into account, in measuring compliance by the member state issuing the letter of notification',
        'for the purposes of measuring compliance with the requirements of this directive concerning national overall targets, the amount of electricity or heating or cooling from renewable energy sources notified in accordance with paragraph 2 shall be reallocated between the concerned member states in accordance with the notified distribution rule',
        'member states shall ensure that guidance is made available to all relevant actors, notably for planners and architects so that they are able properly to consider the optimal combination of renewable energy sources, of high-efficiency technologies and of district heating and cooling when planning, designing, building and renovating industrial or residential areas',
        'member states or the designated competent bodies shall put in place appropriate mechanisms to ensure that guarantees of origin shall be issued, transferred and cancelled electronically and are accurate, reliable and fraud-resistant',
        'where appropriate, member states may require transmission system operators and distribution system operators to bear, in full or in part, the costs referred to in paragraph 3',
        '(a) measuring compliance with the requirements of this directive concerning national targets',
        'with effect from 1 january 2017, the greenhouse gas emission saving from the use of biofuels and bioliquids taken into account for the purposes referred to in points (a), (b) and (c) of paragraph 1 shall be at least 50 %',
        'or (ii) for the protection of rare, threatened or endangered ecosystems or species recognised by international agreements or included in lists drawn up by intergovernmental organisations or the international union for the conservation of nature, subject to their recognition in accordance with the second subparagraph of (4)',
        '(b) continuously forested areas, namely land spanning more than one hectare with trees higher than five metres and a canopy cover of more than 30 %, or trees able to reach those thresholds in situ',
        'and (c) provides for the sum of all consignments withdrawn from the mixture to be described as having the same sustainability characteristics, in the same quantities, as the sum of all consignments added to the mixture',
        'it shall evaluate the frequency and methodology of sampling and the robustness of the data',
        'it shall ensure, in particular, that the provision of that information does not represent an excessive administrative burden for operators in general or for smallholder farmers, producer organisations and cooperatives in particular',
        'where the community has concluded agreements containing provisions relating to matters covered by the sustainability criteria set out in (2) to (5), the commission may decide that those agreements demonstrate that biofuels and bioliquids produced from raw materials cultivated in those countries comply with the sustainability criteria in question',
        'the commission may also recognise areas for the protection of rare, threatened or endangered ecosystems or species recognised by international agreements or included in lists drawn up by intergovernmental organisations or the international union for the conservation of nature for the purposes of (3)(b)(ii)',
        'decisions under paragraph 4 shall be adopted in accordance with the advisory procedure referred to in (3)',
        'or (c) by using a value calculated as the sum of the factors of the formula referred to in point 1 of part c of annex v, where disaggregated default values in part d or e of annex v may be used for some factors, and actual values, calculated in accordance with the methodology laid down in part c of annex v, for all other factors',
        'the default values in part a of annex v for biofuels, and the disaggregated default values for cultivation in part d of annex v for biofuels and bioliquids, may be used only when their raw materials are',
        'the report shall, if appropriate, be accompanied, by a proposal, based on the best available scientific evidence, containing a concrete methodology for emissions from carbon stock changes caused by indirect land-use changes, ensuring compliance with this directive, in particular (2)',
        'annex v may be adapted to technical and scientific progress, including by the addition of values for further biofuel production pathways for the same or for other raw materials and by modifying the methodology laid down in part c',
        'those measures, designed to amend non-essential elements of this directive, inter alia, by supplementing it, shall be adopted in accordance with the regulatory procedure with scrutiny referred to in (4)',
        'the report shall detail, in particular',
        '(b) the introduction and functioning of support schemes and other measures to promote energy from renewable sources, and any developments in the measures used with respect to those set out in the member state’s national renewable energy action plan, and information on how supported electricity is allocated to final customers for purposes of (6) of directive 2003/54/european commission',
        '(g) developments in the availability and use of biomass resources for energy purposes',
        'in estimating net greenhouse gas emission saving from the use of biofuels, the member state may, for the purpose of the reports referred to in paragraph 1, use the typical values given in part a and part b of annex v',
        '(a) establish a single administrative body responsible for processing authorisation, certification and licensing applications for renewable energy installations and providing assistance to applicants',
        'in reporting on greenhouse gas emission saving from the use of biofuels, the commission shall use the values reported by member states and shall evaluate whether and how the estimate would change if co-products were accounted for using the substitution approach',
        '(c) the scope for identifying, in a scientifically objective manner, geographical areas of high biodiversity value that are not covered in (3)',
        'the commission shall, if appropriate, propose corrective action',
        '(v) the evaluation of specific market conditions, considering, in particular, markets on which transport fuels represent more than half of the final energy consumption, and markets which are fully dependent on imported biofuels',
        '(c) technological developments in energy from renewable sources, including the development of the use of biofuels in commercial aviation',
        'except in the cases referred to in paragraph 2, the commission shall be assisted by the committee on renewable energy sources',
        '(5) preliminary estimates, carried out with a view to assessing the impact of the directive and referred to in the impact assessment of the commission, indicate that seven million tonnes of co 2 could be stored by 2020, and up to 160 million tonnes by 2030, assuming a 20 % reduction in greenhouse gas emissions by 2020 and provided that ccs obtains private, national and community support and proves to be an environmentally safe technology',
        'the communication set out an action plan for the commission in this area during 2007, which required the development of a sound management framework for ccs, including the work on the regulatory framework, incentive framework, and support programmes, as well as external elements, for example technology cooperation with key countries on ccs',
        '(9) the european council of march 2008 recalled that the objective of proposing a regulatory framework on ccs was to ensure that this novel technology would be deployed in an environmentally safe way',
        '(12) at the international level, legal barriers to the geological storage of co 2 in geological formations under the seabed have been removed through the adoption of related risk management frameworks under the 1996 london protocol to the 1972 convention on the prevention of marine pollution by dumping of wastes and other matter (1996 london protocol) and under the convention for the protection of the marine environment of the north-east atlantic (ospar convention)',
        '(13) in 2006, the contracting parties to the 1996 london protocol adopted amendments to the protocol',
        'they also adopted a decision to prohibit placement of co 2 into the water-column of the sea and on the seabed, because of the potential negative effects',
        'this threshold would also seem appropriate for the purposes of other relevant community legislation',
        'this includes the right of member states not to allow any storage in parts or on the whole of their territory, or to give priority to any other use of the underground, such as exploration, production and storage of hydrocarbons or geothermal use of aquifers',
        'in the granting of the storage permit, priority should be given to the holder of the exploration permit over competitors, as the former will generally have made substantial investments',
        'the national authorities should take this opinion into consideration when taking a decision on the permit and should justify any departure from the commission’s opinion',
        'after the withdrawal of a permit, the competent authority should either issue a new permit or close the storage site',
        'inclusion of capture installations in directive 2008/1/european commission further ensures that best available techniques to improve the composition of the co 2 stream have to be established and applied',
        '(35) after the transfer of responsibility, monitoring should be reduced to a level which still allows for identification of leakages or significant irregularities, but should again be intensified if leakages or significant irregularities are identified',
        'those penalties should be effective, proportionate and dissuasive',
        'for this reason, directive 2006/12/european commission of the european parliament and of the council of 5 april 2006 on waste and regulation no 1013/2006 of the european parliament and of the council of 14 june 2006 on shipments of waste should be amended so as to exclude co 2 captured and transported for the purposes of geological storage from the scope of application of those instruments',
        'to this end, directive 2001/80/european commission of the european parliament and of the council of 23 october 2001 on the limitation of emissions of certain pollutants into the air from large combustion plants should be amended to require that all combustion plants of a specified capacity, for which the original construction licence or the original operating licence is granted after the entry into force of this directive, have suitable space on the installation site for the equipment necessary to capture and compress co 2 if suitable storage sites are available, and if co 2 transport and retrofitting for co 2 capture are technically and economically feasible',
        '‘geological storage of co 2 ’ means injection accompanied by storage of co 2 streams in underground geological formations',
        '‘substantial change’ means any change not provided for in the storage permit, which may have significant effects on the environment or human health',
        '‘closure’ of a storage site means the definitive cessation of co 2 injection into that storage site',
        'the duration of a permit shall not exceed the period necessary to carry out the exploration for which it is granted',
        'within four months after receipt of the draft storage permit, the commission may issue a non-binding opinion on it',
        'if the commission decides not to issue an opinion, it shall inform the member state within one month of submission of the draft permit and state its reasons',
        'the competent authority shall review and where necessary update or, as a last resort, withdraw the storage permit',
        '(b) if the reports submitted pursuant to or the environmental inspections carried out pursuant to show non-compliance with permit conditions or risks of leakages or significant irregularities',
        'or (e) without prejudice to points (a) to (d), five years after issuing the permit and every 10 years thereafter',
        '(a) adversely affect the integrity of the storage site or the relevant transport infrastructure',
        '(a) accepts and injects co 2 streams only if an analysis of the composition, including corrosive substances, of the streams and a risk assessment have been carried out, and if the risk assessment has shown that the contamination levels are in line with the conditions referred to in paragraph 1',
        'the monitoring shall be based on a monitoring plan designed by the operator pursuant to the requirements laid down in annex ii, including details on the monitoring in accordance with the guidelines established pursuant to and (2) of directive 2003/87/european commission, submitted to and approved by the competent authority pursuant to (6) and (5) of this directive',
        '(b) if the reports pursuant to have shown insufficient compliance with the permit conditions',
        'the competent authority may also at any time take corrective measures itself',
        'a provisional post-closure plan shall be submitted to and approved by the competent authority pursuant to (8) and (7)',
        '(b) the proportion of its co 2 reduction obligations pursuant to international legal instruments and to community legislation that it intends to meet through capture and geological storage of co 2',
        'the first report shall be sent to the commission by 30 june 2011',
        'the member states shall notify those provisions to the commission by 25 june 2011 and shall notify it without delay of any subsequent amendment affecting them',
        'the commission shall be assisted by the climate change committee',
        '— for the transport of gas, oil, chemicals, and, — for the transport of carbon dioxide (co 2 ) streams for the purposes of geological storage, including associated booster stations',
        'in directive 2001/80/european commission, the following shall be inserted',
        'the operation of storage sites pursuant to directive 2009/31/european commission of the european parliament and of the council of 23 april 2009 on the geological storage of carbon dioxide',
        '‘(a) gaseous effluents emitted into the atmosphere and carbon dioxide captured and transported for the purposes of geological storage and geologically stored in accordance with directive 2009/31/european commission of the european parliament and of the council of 23 april 2009 on the geological storage of carbon dioxide or excluded from the scope of that directive pursuant to its (2)'
        'member states shall communicate to the commission the text of the main provisions of national law which they adopt in the field covered by this directive',
        'this directive shall enter into force on the 20th day following its publication in the official journal of the european union']